version: "3.8"
services:
  crawlers:
    container_name: property_crawler
    build: .
    command: sh -c "cd property_crawler/property_crawler; scrapy list|xargs -n 1 scrapy crawl"
    volumes:
      - ./property_crawler/:/property_crawler
    ports:
      - 6800:6800
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: property_db
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - property_crawlers:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      LANG: "pl_PL.UTF-8"
      LANGUAGE: "pl_PL.UTF-8"
      LC_ALL: "pl_PL.UTF-8"
      LC_COLLATE: "pl_PL.UTF-8"
      LC_CTYPE: "pl_PL.UTF-8"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  property_crawlers:
